CREATE TABLE IF NOT EXISTS user (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL DEFAULT '',
    uuid VARCHAR(255) NOT NULL DEFAULT '',
    authenticated BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    authenticated_at TIMESTAMPTZ DEFAULT NULL
)
